### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Vitoshka** [vendethiel/wotlk-partyabilitybars#8]
10x PAB-1.12\PAB.lua:648: bad argument #1 to 'pairs' (table expected, got nil)
PAB-1.12\PAB.lua:648: in function `UpdateAnchors'
PAB-1.12\PAB.lua:1175: in function `changeFunc'
LibSimpleOptions-1.0-90043:603: in function `SetValue'
LibSimpleOptions-1.0-90043:608: in function <...B\libs\LibSimpleOptions-1.0\LibSimpleOptions-1.0.lua:607>

Locals:
self = PAB {
 0 = <userdata>
 LoadPositions = <function> @ PAB\PAB.lua:512:
 StopAllIcons = <function> @ PAB\PAB.lua:902:
 QuerySpecInfo = <function> @ PAB\PAB.lua:824:
 PLAYER_ENTERING_WORLD = <function> @ PAB\PAB.lua:722:
 HideUnusedAnchors = <function> @ PAB\PAB.lua:610:
 abilityStore = <table> {}
 scrollframe = PABScrollFrame {}
 FormatAbility = <function> @ PAB\PAB.lua:967:
 CheckAbility = <function> @ PAB\PAB.lua:735:
 CreateAnchors = <function> @ PAB\PAB.lua:531:
 panel = PAB_Panel {}
 PARTY_MEMBERS_CHANGED = <function> @ PAB\PAB.lua:714:
 ResetAnchorsSpec = <function> @ PAB\PAB.lua:624:
 SavePositions = <function> @ PAB\PAB.lua:496:
 ShowUsedAnchors = <function> @ PAB\PAB.lua:606:
 Schedule = <function> @ PAB\PAB.lua:772:
 UpdateAnchors = <function> @ PAB\PAB.lua:630:
 btns = <table> {}
 CreateOptions = <function> @ PAB\PAB.lua:992:
 HideUnusedIcons = <function> @ PAB\PAB.lua:617:
 FindAbilityIcon = <function> @ PAB\PAB.lua:956:
 UpdateAnchorIcon = <function> @ PAB\PAB.lua:672:
 ApplyAnchorSettings = <function> @ PAB\PAB.lua:688:
 UpdateScrollBar = <function> @ PAB\PAB.lua:1128:
 AppendIcon = <function> @ PAB\PAB.lua:592:
 UNIT_SPELLCAST_SUCCEEDED = <function> @ PAB\PAB.lua:759:
 CreateAbilityEditor = <function> @ PAB\PAB.lua:1160:
}
updateIcons = true
(for index) = 3
(for limit) = 4
(for step) = 1
i = 3
_ = "Шаманка"
class = "SHAMAN"
anchor = PABAnchor3 {
 GUID = "0x0000000000021C48"
 race = "Goblin"
 spec = <table> {}
 0 = <userdata>
 class = "SHAMAN"
 icons = <table> {}
 HideIcons = <function> @ PAB\PAB.lua:542:
}
numIcons = 1
GetNumPartyMembers = <function> defined =[C]:-1
UnitClass = <function> @ Interface\SharedXML\FunctionOverride.lua:22:
anchors = <table> {
 1 = PABAnchor1 {}
 2 = PABAnchor2 {}
 3 = PABAnchor3 {}
 4 = PABAnchor4 {}
}
UnitGUID = <function> defined =[C]:-1
db = <table> {
 iconsperline = 0
 classSelected = "PALADIN"
 scale = 0.94999998807907
 hidden = true
 xanchor = -88
 movable = true
 abilities = <table> {}
 lock = true
 enabledCooldowns = <table> {}
 arena = true
 positions = <table> {}
 yanchor = 17
}
specAbilities = <table> {
 DEATHKNIGHT = <table> {}
 WARRIOR = <table> {}
 ROGUE = <table> {}
 MAGE = <table> {}
 PRIEST = <table> {}
 WARLOCK = <table> {}
 PALADIN = <table> {}
 DRUID = <table> {}
 SHAMAN = <table> {}
 HUNTER = <table> {}
}

  ---

**Comment by Vitoshka** [comment]
11x PAB-1.12\PAB.lua:766: attempt to index field '?' (a nil value)
PAB-1.12\PAB.lua:911: in function <PAB\PAB.lua:911>

Locals:
self = PAB {
 0 = <userdata>
 LoadPositions = <function> @ PAB\PAB.lua:512:
 StopAllIcons = <function> @ PAB\PAB.lua:902:
 QuerySpecInfo = <function> @ PAB\PAB.lua:824:
 PLAYER_ENTERING_WORLD = <function> @ PAB\PAB.lua:722:
 HideUnusedAnchors = <function> @ PAB\PAB.lua:610:
 abilityStore = <table> {}
 scrollframe = PABScrollFrame {}
 FormatAbility = <function> @ PAB\PAB.lua:967:
 CheckAbility = <function> @ PAB\PAB.lua:735:
 CreateAnchors = <function> @ PAB\PAB.lua:531:
 panel = PAB_Panel {}
 PARTY_MEMBERS_CHANGED = <function> @ PAB\PAB.lua:714:
 ResetAnchorsSpec = <function> @ PAB\PAB.lua:624:
 SavePositions = <function> @ PAB\PAB.lua:496:
 ShowUsedAnchors = <function> @ PAB\PAB.lua:606:
 Schedule = <function> @ PAB\PAB.lua:772:
 UpdateAnchors = <function> @ PAB\PAB.lua:630:
 btns = <table> {}
 CreateOptions = <function> @ PAB\PAB.lua:992:
 HideUnusedIcons = <function> @ PAB\PAB.lua:617:
 FindAbilityIcon = <function> @ PAB\PAB.lua:956:
 UpdateAnchorIcon = <function> @ PAB\PAB.lua:672:
 ApplyAnchorSettings = <function> @ PAB\PAB.lua:688:
 UpdateScrollBar = <function> @ PAB\PAB.lua:1128:
 AppendIcon = <function> @ PAB\PAB.lua:592:
 UNIT_SPELLCAST_SUCCEEDED = <function> @ PAB\PAB.lua:759:
 CreateAbilityEditor = <function> @ PAB\PAB.lua:1160:
}
event = "UNIT_SPELLCAST_SUCCEEDED"

  ---

**Comment by Vitoshka** [comment]
1x PAB-1.12\PAB.lua:648: bad argument #1 to 'pairs' (table expected, got nil)
PAB-1.12\PAB.lua:648: in function `UpdateAnchors'
PAB-1.12\PAB.lua:731: in function `?'
PAB-1.12\PAB.lua:911: in function <PAB\PAB.lua:911>

Locals:
self = PAB {
 0 = <userdata>
 LoadPositions = <function> @ PAB\PAB.lua:512:
 StopAllIcons = <function> @ PAB\PAB.lua:902:
 QuerySpecInfo = <function> @ PAB\PAB.lua:824:
 PLAYER_ENTERING_WORLD = <function> @ PAB\PAB.lua:722:
 HideUnusedAnchors = <function> @ PAB\PAB.lua:610:
 abilityStore = <table> {}
 scrollframe = PABScrollFrame {}
 FormatAbility = <function> @ PAB\PAB.lua:967:
 CheckAbility = <function> @ PAB\PAB.lua:735:
 CreateAnchors = <function> @ PAB\PAB.lua:531:
 panel = PAB_Panel {}
 PARTY_MEMBERS_CHANGED = <function> @ PAB\PAB.lua:714:
 ResetAnchorsSpec = <function> @ PAB\PAB.lua:624:
 SavePositions = <function> @ PAB\PAB.lua:496:
 ShowUsedAnchors = <function> @ PAB\PAB.lua:606:
 Schedule = <function> @ PAB\PAB.lua:772:
 UpdateAnchors = <function> @ PAB\PAB.lua:630:
 btns = <table> {}
 CreateOptions = <function> @ PAB\PAB.lua:992:
 HideUnusedIcons = <function> @ PAB\PAB.lua:617:
 FindAbilityIcon = <function> @ PAB\PAB.lua:956:
 UpdateAnchorIcon = <function> @ PAB\PAB.lua:672:
 ApplyAnchorSettings = <function> @ PAB\PAB.lua:688:
 UpdateScrollBar = <function> @ PAB\PAB.lua:1128:
 AppendIcon = <function> @ PAB\PAB.lua:592:
 UNIT_SPELLCAST_SUCCEEDED = <function> @ PAB\PAB.lua:759:
 CreateAbilityEditor = <function> @ PAB\PAB.lua:1160:
}
updateIcons = false
(for index) = 2
(for limit) = 4
(for step) = 1
i = 2
_ = "Æðåö"
class = "PRIEST"
anchor = PABAnchor2 {
 GUID = "0x00000000000075B6"
 race = "Goblin"
 0 = <userdata>
 class = "PRIEST"
 icons = <table> {}
 HideIcons = <function> @ PAB\PAB.lua:542:
}
numIcons = 1
GetNumPartyMembers = <function> defined =[C]:-1
UnitClass = <function> @ Interface\SharedXML\FunctionOverride.lua:22:
anchors = <table> {
 1 = PABAnchor1 {}
 2 = PABAnchor2 {}
 3 = PABAnchor3 {}
 4 = PABAnchor4 {}
}
UnitGUID = <function> defined =[C]:-1
db = <table> {
 iconsperline = 0
 classSelected = "PALADIN"
 scale = 0.89999997615814
 hidden = true
 xanchor = -88
 movable = true
 abilities = <table> {}
 lock = true
 enabledCooldowns = <table> {}
 arena = false
 positions = <table> {}
 yanchor = 17
}
specAbilities = <table> {
 DEATHKNIGHT = <table> {}
 WARRIOR = <table> {}
 ROGUE = <table> {}
 MAGE = <table> {}
 PRIEST = <table> {}
 WARLOCK = <table> {}
 PALADIN = <table> {}
 DRUID = <table> {}
 SHAMAN = <table> {}
 HUNTER = <table> {}
}

  ---

**Comment by vendethiel** [comment]
Reset your PAB config, remove the SavedVariables for PAB.
