### ISSUE TITLE
Conflict Addon Skin

### ISSUE THREAD

**Issue by Vitoshka** [vendethiel/wotlk-partyabilitybars#9]
**Conflict Addon Skin [ElvUi Sirus](https://github.com/sirus-addons/ElvUI) with PartyAbilityBars**

1x ElvUI_AddOnSkins-1.02\Skins\Addons\pab.lua:21: attempt to index field 'PABScrollFrameAbility name' (a nil value)
<string>:"safecall Dispatcher[1]":4: in function <[string "safecall Dispatcher[1]"]:4>
<in C code>: ?
<string>:"safecall Dispatcher[1]":13: in function `?'
CallbackHandler-1.0-6 (Ace3):92: in function `Fire'
ElvUI-5.50\modules\skins\skins.lua:607: in function `Initialize'
ElvUI-5.50\modules\skins\skins.lua:641: in function <ElvUI\modules\skins\skins.lua:640>
CallbackHandler-1.0-6 (Ace3):157: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:157>
<string>:"safecall Dispatcher[1]":4: in function <[string "safecall Dispatcher[1]"]:4>
<in C code>: ?
<string>:"safecall Dispatcher[1]":13: in function `?'
CallbackHandler-1.0-6 (Ace3):92: in function `Fire'
ElvUI-5.50\core\core.lua:1103: in function `InitializeModules'
ElvUI-5.50\core\core.lua:1246: in function `Initialize'
ElvUI-5.50\init.lua:128: in function <ElvUI\init.lua:127>

  ---

**Comment by vendethiel** [comment]
That's on ElvUI.
